springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  datasource:
    url: ${DB_URL}
    
  flyway:
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  temp:
    cookie:
      expiration: ${JWT_TEMP_COOKIE_EXPIRATION:5m}
  access:
    cookie:
      expiration: ${JWT_ACCESS_COOKIE_EXPIRATION:15m}
  refresh:
    cookie:
      expiration: ${JWT_REFRESH_COOKIE_EXPIRATION:7d}
