spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    baseline-on-migrate: false
  
  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.enigmazer.clef: trace
jwt:
  temp:
    cookie:
      expiration: ${JWT_TEMP_COOKIE_EXPIRATION:5m}
  access:
    cookie:
      expiration: ${JWT_ACCESS_COOKIE_EXPIRATION:15m}
  refresh:
    cookie:
      expiration: ${JWT_REFRESH_COOKIE_EXPIRATION:7d}
