spring:
  datasource:
    url: ${DB_URL}

  flyway:
    baseline-on-migrate: false
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
          hibernate:
            query:
              fail_on_pagination_over_collection_fetch: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.enigmazer.clef: trace
jwt:
  temp:
    cookie:
      expiration: 5m
  access:
    cookie:
      expiration: 1d
  refresh:
    cookie:
      expiration: 7d
